import { NextResponse } from "next/server";
import { createReadStream } from "node:fs";
import fs from "node:fs/promises";
import { Readable } from "node:stream";

import { prisma } from "@/server/db";
import { recordAuditEvent } from "@/server/audit/log";
import { clientIpFrom } from "@/server/http/client";
import { requirePermission } from "@/server/permissions";
import { archivePath } from "@/server/backups/paths";

/**
 * Downloads one backup archive.
 *
 * The archive holds every table — staff password hashes and enquiries
 * included — so it is behind its own permission, streamed rather than
 * buffered, never cached, and every download is audited.
 */
export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const actor = await requirePermission("BACKUPS", "EXPORT");

  const { id } = await params;
  const backup = await prisma.backup.findUnique({
    where: { id },
    select: { id: true, filename: true, status: true },
  });
  if (!backup || backup.status !== "COMPLETED") {
    return new NextResponse("Not found", { status: 404 });
  }

  let file: string;
  let size: number;
  try {
    file = archivePath(backup.filename);
    size = (await fs.stat(file)).size;
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }
  await recordAuditEvent({
    actorId: actor.id,
    actorEmail: actor.email,
    action: "BACKUP_DOWNLOADED",
    module: "BACKUPS",
    entityType: "Backup",
    entityId: backup.id,
    summary: `Backup ${backup.filename} downloaded`,
    ipAddress: clientIpFrom(request.headers),
    userAgent: request.headers.get("user-agent"),
  });

  const stream = Readable.toWeb(createReadStream(file)) as ReadableStream;
  return new NextResponse(stream, {
    headers: {
      "Content-Type": "application/gzip",
      "Content-Length": String(size),
      // The name is generated by the application and matches a fixed pattern.
      "Content-Disposition": `attachment; filename="${backup.filename}"`,
      "X-Content-Type-Options": "nosniff",
      "Cache-Control": "private, no-store",
    },
  });
}
